/**
 * Client KB Module Constants
 * Error codes and error messages
 */

export const CLIENT_KB_ERROR_CODES = {
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_NAME_REQUIRED: 'CLIENT_NAME_REQUIRED',
  CLIENT_NAME_TOO_LONG: 'CLIENT_NAME_TOO_LONG',
  INVALID_CLIENT_ID: 'INVALID_CLIENT_ID',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  CONTEXT_SUMMARY_UPDATE_FAILED: 'CONTEXT_SUMMARY_UPDATE_FAILED',
  CLIENT_ALREADY_EXISTS: 'CLIENT_ALREADY_EXISTS',
  CANNOT_TRANSFER_TO_SELF: 'CANNOT_TRANSFER_TO_SELF',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const;

export const CLIENT_KB_ERROR_MESSAGES = {
  [CLIENT_KB_ERROR_CODES.CLIENT_NOT_FOUND]: 'Client not found',
  [CLIENT_KB_ERROR_CODES.CLIENT_NAME_REQUIRED]: 'Client name is required',
  [CLIENT_KB_ERROR_CODES.CLIENT_NAME_TOO_LONG]: 'Client name is too long',
  [CLIENT_KB_ERROR_CODES.INVALID_CLIENT_ID]: 'Invalid client ID format',
  [CLIENT_KB_ERROR_CODES.UNAUTHORIZED_ACCESS]: 'Unauthorized access to client',
  [CLIENT_KB_ERROR_CODES.CONTEXT_SUMMARY_UPDATE_FAILED]: 'Failed to update client context summary',
  [CLIENT_KB_ERROR_CODES.CLIENT_ALREADY_EXISTS]: 'Client with this name already exists',
  [CLIENT_KB_ERROR_CODES.CANNOT_TRANSFER_TO_SELF]: 'Cannot transfer ownership to yourself',
  [CLIENT_KB_ERROR_CODES.USER_NOT_FOUND]: 'User not found',
} as const;

export const CLIENT_KB_CONSTANTS = {
  MAX_NAME_LENGTH: 255,
  MIN_NAME_LENGTH: 1,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;

export type ClientKBErrorCode = (typeof CLIENT_KB_ERROR_CODES)[keyof typeof CLIENT_KB_ERROR_CODES];








