/**
 * Scenario Module Constants
 * Error codes, error messages, and limits
 */

export const SCENARIO_ERROR_CODES = {
  SCENARIO_NOT_FOUND: 'SCENARIO_NOT_FOUND',
  INVALID_SCENARIO_ID: 'INVALID_SCENARIO_ID',
  NAME_REQUIRED: 'NAME_REQUIRED',
  NAME_TOO_LONG: 'NAME_TOO_LONG',
  SYSTEM_PROMPT_REQUIRED: 'SYSTEM_PROMPT_REQUIRED',
  SYSTEM_PROMPT_TOO_LONG: 'SYSTEM_PROMPT_TOO_LONG',
  OUTPUT_SCHEMA_REQUIRED: 'OUTPUT_SCHEMA_REQUIRED',
  OUTPUT_SCHEMA_INVALID: 'OUTPUT_SCHEMA_INVALID',
  ARTIFACTS_CONFIG_REQUIRED: 'ARTIFACTS_CONFIG_REQUIRED',
  ARTIFACTS_CONFIG_INVALID: 'ARTIFACTS_CONFIG_INVALID',
  MEETING_TYPE_NOT_FOUND: 'MEETING_TYPE_NOT_FOUND',
  INVALID_MEETING_TYPE_ID: 'INVALID_MEETING_TYPE_ID',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  SCENARIO_IN_USE: 'SCENARIO_IN_USE',
  MEETING_TYPE_IN_USE: 'MEETING_TYPE_IN_USE',
  MEETING_TYPE_NOT_FOUND: 'MEETING_TYPE_NOT_FOUND',
  MEETING_TYPE_NAME_REQUIRED: 'MEETING_TYPE_NAME_REQUIRED',
  MEETING_TYPE_NAME_TOO_LONG: 'MEETING_TYPE_NAME_TOO_LONG',
  KEYTERMS_INVALID: 'KEYTERMS_INVALID',
  KEYTERMS_TOO_MANY: 'KEYTERMS_TOO_MANY',
  KEYTERM_TOO_LONG: 'KEYTERM_TOO_LONG',
} as const;

export const SCENARIO_ERROR_MESSAGES = {
  [SCENARIO_ERROR_CODES.SCENARIO_NOT_FOUND]: 'Scenario not found',
  [SCENARIO_ERROR_CODES.INVALID_SCENARIO_ID]: 'Invalid scenario ID format',
  [SCENARIO_ERROR_CODES.NAME_REQUIRED]: 'Scenario name is required',
  [SCENARIO_ERROR_CODES.NAME_TOO_LONG]: 'Scenario name is too long',
  [SCENARIO_ERROR_CODES.SYSTEM_PROMPT_REQUIRED]: 'System prompt is required',
  [SCENARIO_ERROR_CODES.SYSTEM_PROMPT_TOO_LONG]: 'System prompt is too long',
  [SCENARIO_ERROR_CODES.OUTPUT_SCHEMA_REQUIRED]: 'Output schema is required',
  [SCENARIO_ERROR_CODES.OUTPUT_SCHEMA_INVALID]: 'Output schema must be valid JSON',
  [SCENARIO_ERROR_CODES.ARTIFACTS_CONFIG_REQUIRED]: 'Artifacts config is required',
  [SCENARIO_ERROR_CODES.ARTIFACTS_CONFIG_INVALID]: 'Artifacts config must be valid JSON',
  [SCENARIO_ERROR_CODES.MEETING_TYPE_NOT_FOUND]: 'Meeting type not found',
  [SCENARIO_ERROR_CODES.INVALID_MEETING_TYPE_ID]: 'Invalid meeting type ID format',
  [SCENARIO_ERROR_CODES.UNAUTHORIZED_ACCESS]: 'Unauthorized access. Only Admin can manage scenarios',
  [SCENARIO_ERROR_CODES.SCENARIO_IN_USE]: 'Scenario is in use and cannot be deleted',
  [SCENARIO_ERROR_CODES.MEETING_TYPE_IN_USE]: 'Meeting type is in use and cannot be deleted',
  [SCENARIO_ERROR_CODES.MEETING_TYPE_NAME_REQUIRED]: 'Meeting type name is required',
  [SCENARIO_ERROR_CODES.MEETING_TYPE_NAME_TOO_LONG]: 'Meeting type name is too long',
  [SCENARIO_ERROR_CODES.KEYTERMS_INVALID]: 'Keyterms must be an array of strings',
  [SCENARIO_ERROR_CODES.KEYTERMS_TOO_MANY]: 'Maximum 100 keyterms allowed',
  [SCENARIO_ERROR_CODES.KEYTERM_TOO_LONG]: 'Each keyterm must be no longer than 200 characters',
} as const;

export const SCENARIO_CONSTANTS = {
  MAX_NAME_LENGTH: 255,
  MIN_NAME_LENGTH: 1,
  MAX_SYSTEM_PROMPT_LENGTH: 50000, // 50KB for system prompt
  MIN_SYSTEM_PROMPT_LENGTH: 10,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  MAX_MEETING_TYPE_NAME_LENGTH: 255,
  MAX_KEYTERMS_COUNT: 100, // Deepgram supports up to 100 keyterms
  MAX_KEYTERM_LENGTH: 200, // Maximum length per keyterm
} as const;

export type ScenarioErrorCode = (typeof SCENARIO_ERROR_CODES)[keyof typeof SCENARIO_ERROR_CODES];


