/**
 * Directory Module Constants
 * Error codes and error messages
 */

export const DIRECTORY_ERROR_CODES = {
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  FULL_NAME_REQUIRED: 'FULL_NAME_REQUIRED',
  FULL_NAME_TOO_LONG: 'FULL_NAME_TOO_LONG',
  INVALID_PARTICIPANT_ID: 'INVALID_PARTICIPANT_ID',
  INVALID_PARTICIPANT_TYPE: 'INVALID_PARTICIPANT_TYPE',
  COMPANY_NAME_REQUIRED_FOR_EXTERNAL: 'COMPANY_NAME_REQUIRED_FOR_EXTERNAL',
  DEPARTMENT_REQUIRED_FOR_INTERNAL: 'DEPARTMENT_REQUIRED_FOR_INTERNAL',
  INVALID_TAGS_FORMAT: 'INVALID_TAGS_FORMAT',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  PARTICIPANT_ALREADY_EXISTS: 'PARTICIPANT_ALREADY_EXISTS',
} as const;

export const DIRECTORY_ERROR_MESSAGES = {
  [DIRECTORY_ERROR_CODES.PARTICIPANT_NOT_FOUND]: 'Participant not found',
  [DIRECTORY_ERROR_CODES.FULL_NAME_REQUIRED]: 'Full name is required',
  [DIRECTORY_ERROR_CODES.FULL_NAME_TOO_LONG]: 'Full name is too long',
  [DIRECTORY_ERROR_CODES.INVALID_PARTICIPANT_ID]: 'Invalid participant ID format',
  [DIRECTORY_ERROR_CODES.INVALID_PARTICIPANT_TYPE]: 'Invalid participant type. Must be "internal" or "external"',
  [DIRECTORY_ERROR_CODES.COMPANY_NAME_REQUIRED_FOR_EXTERNAL]: 'Company name is required for external participants',
  [DIRECTORY_ERROR_CODES.DEPARTMENT_REQUIRED_FOR_INTERNAL]: 'Department is required for internal participants',
  [DIRECTORY_ERROR_CODES.INVALID_TAGS_FORMAT]: 'Tags must be a valid JSON object or array',
  [DIRECTORY_ERROR_CODES.UNAUTHORIZED_ACCESS]: 'Unauthorized access to participant',
  [DIRECTORY_ERROR_CODES.PARTICIPANT_ALREADY_EXISTS]: 'Participant with this name already exists',
} as const;

export const DIRECTORY_CONSTANTS = {
  MAX_FULL_NAME_LENGTH: 255,
  MIN_FULL_NAME_LENGTH: 1,
  MAX_ROLE_TITLE_LENGTH: 255,
  MAX_COMPANY_NAME_LENGTH: 255,
  MAX_DEPARTMENT_LENGTH: 255,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
} as const;

export type DirectoryErrorCode = (typeof DIRECTORY_ERROR_CODES)[keyof typeof DIRECTORY_ERROR_CODES];








